DROP DATABASE IF EXISTS `POKER`;
CREATE DATABASE `POKER`
    CHARACTER SET utf8
    COLLATE utf8_bin;
USE `POKER`;

CREATE TABLE `USERS` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(128) NOT NULL,
    `LAST_NAME` VARCHAR(128) NULL,
    `EMAIL` VARCHAR(254) NULL,
    `EXTERNAL_ID` VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE `SESSIONS` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(128) NOT NULL,
    `CODE` VARCHAR(35) NOT NULL UNIQUE,
    `CREATED` TIMESTAMP NOT NULL,
    `DESCRIPTION` VARCHAR(4096) NULL,
    `ESTIMATES` VARCHAR(1024) NOT NULL,
    `AUTHOR_ID` BIGINT NOT NULL,
    FOREIGN KEY (`AUTHOR_ID`)
        REFERENCES `USERS` (`ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `ITEMS` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `TITLE` VARCHAR(128) NOT NULL,
    `DESCRIPTION` VARCHAR(4096) NULL,
    `SESSION_ID` BIGINT NOT NULL,
    FOREIGN KEY (`SESSION_ID`)
        REFERENCES `SESSIONS` (`ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `ESTIMATES` (
    `ITEM_ID` BIGINT NOT NULL,
    `USER_ID` BIGINT NOT NULL,
    `ESTIMATE` INT NOT NULL,
    FOREIGN KEY (`ITEM_ID`)
        REFERENCES `ITEMS` (`ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`)
        REFERENCES `USERS` (`ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (`USER_ID`, `ITEM_ID`)
);

